# Word embedding using keras embedding layer

Food review classification and word embeddings are calculated.



1.   Take a fake problem, here it is food review classification.
2.   Solve it using neural network.
3.   Get word embeddings as a side effect.



In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

# example reviews
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

# 1 for poitive review, 0 for negative review
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("too good",30)

[14, 25]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[5, 7], [3, 9], [14, 25], [19, 15, 18], [28, 5, 29], [26, 7], [13, 5, 4], [12, 19], [12, 12], [20, 28]]


In [4]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 5  7  0]
 [ 3  9  0]
 [14 25  0]
 [19 15 18]
 [28  5 29]
 [26  7  0]
 [13  5  4]
 [12 19  0]
 [12 12  0]
 [20 28  0]]


In [5]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 205ms/step - loss: 0.6306 - accuracy: 1.0000


1.0

In [10]:
#get the weights
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[7]

array([ 0.03490022,  0.00623784, -0.04179415,  0.01157369], dtype=float32)

In [12]:
weights[27]

array([-0.0218966 , -0.04060773, -0.00225751,  0.02452675], dtype=float32)